### PR TITLE
lol I made a typo in my own last name

### PR DESCRIPTION
**Pull request by ikonst**

### CODE REVIEW

**Comment by ikonst** [comment]
@efine can take a look?

**Comment by efine** [comment]
@ikonst, I would do this, but sadly, I no longer work for the company. Possibly @skorokithakis could help.

**Comment by skorokithakis** [comment]
I would be happy to merge this, but can you amend the commit message to something cleaner? Thanks!

**Comment by ikonst** [comment]
@skorokithakis fixed

**Comment by skorokithakis** [comment]
Thank you!

**Pull request merged**
